genome: /abs/path/dev/ChimAnn/example/input/S_pombe/genome.fna
rnaseq: /abs/path/rnaseq.list      # lines: /abs/path/R1.fastq /abs/path/R2.fastq fastq
proteins: /abs/path/related_proteins.faa
outdir: /abs/path/dev/ChimAnn/example/output
threads: 16
# siteval_init: /abs/path/dev/siteval/models/ssm-hsap-v8s5-with_chr1   # fine-tune from pretrained weights
